### ISSUE TITLE
iOS command to start Repl is not working 

### ISSUE THREAD

**Issue by KranthiReddyK** [mobileboxlab/appium-java-repl#2]
`java> ios.start("iPhone-7", "EE7A251E-1AEE-4BE1-AF41-77F616C00958", "/Users/kranthi/Library/Developer/Xcode/DerivedData/path/to/example.app", "http://0.0.0.0:4723/wd/hub", "1200")` is the command I gave and returned the result.

I have started Appium session before running the above command.

`ERROR: start(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) is not public in com.mobilebox.repl.commands.IOSCommands; cannot be accessed from outside package
    ios.start("iPhone-7", "EE7A251E-1AEE-4BE1-AF41-77F616C00958", /Users/kranthi/Library/Developer/Xcode/DerivedData/path/to/example.app", "http://0.0.0.0:4723/wd/hub", "1200");
       ^

ERROR: start(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) is not public in com.mobilebox.repl.commands.IOSCommands; cannot be accessed from outside package
    ios.start("iPhone-7", "EE7A251E-1AEE-4BE1-AF41-77F616C00958", /Users/kranthi/Library/Developer/Xcode/DerivedData/path/to/example.app", "http://0.0.0.0:4723/wd/hub", "1200");
       ^
ERROR: incompatible types: void cannot be converted to java.lang.Object
    ios.start("iPhone-7", "EE7A251E-1AEE-4BE1-AF41-77F616C00958", /Users/kranthi/Library/Developer/Xcode/DerivedData/path/to/example.app", "http://0.0.0.0:4723/wd/hub", "1200");`

**Comment by dev-mobileboxlab** [comment]
Hi @KranthiReddyK.  

Could you please check this [v0.2.0-BETA1](https://github.com/mobileboxlab/appium-java-repl/releases/tag/v0.2.0-BETA1) version of Appium Java Repl?

Thank you.

**Comment by KranthiReddyK** [comment]
@dev-mobileboxlab I just tried the BETA1 still has some issues. Please find the logs below.

## Link to iOS REPL logs

https://gist.github.com/KranthiReddyK/584a8b42698ba074b8635ab382b58687

## Link to Appium logs

https://gist.github.com/KranthiReddyK/95acb0930535f858c06346d7d8cc4179

**Comment by KranthiReddyK** [comment]
@dev-mobileboxlab  Never mind I forgot to use `--automation-name` as part of server argument when starting Appium.

**Comment by KranthiReddyK** [comment]
Issue resolved Thanks

**Comment by dev-mobileboxlab** [comment]
@KranthiReddyK Thank you for your kind cooperation.
