### ISSUE TITLE
Not able to click on a element on iOS REPL session

### ISSUE THREAD

**Issue by KranthiReddyK** [mobileboxlab/appium-java-repl#3]
java> ios.byId("WelcomeStarted").get(0).click()
[HTTP] --> POST /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/elements {"using":"id","value":"WelcomeStarted"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["id","WelcomeStarted","4ccec28c-7c15-4242-9522-fbecfa4ae206"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/elements] with body: {"using":"id","value":"WelcomeStarted"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5","type":"XCUIElementTypeButton","label":"Get Started"}],"sessionId":"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5","type":"XCUIElementTypeButton","label":"Get Started"}]
[HTTP] <-- POST /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/elements 200 267 ms - 177 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206 {}
[debug] [MJSONWP] Calling AppiumDriver.getSession() with args: ["4ccec28c-7c15-4242-9522-fbecfa4ae206"]
[debug] [XCUITest] Executing command 'getSession'
[debug] [JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"LifeQA\",\n      \"sdkVersion\" : \"10.2\",\n      \"CFBundleIdentifier\" : \"com.life360.safetymap\"\n    }\n  },\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"udid":"EE7A251E-1AEE-4BE1-AF41-77F616C00958","app":"/Users/kranthi/Library/Developer/Xcode/DerivedData/SafetyMap-bepmknmoanbjekfkcdcesdxbonff/Build/Products/Debug-iphonesimulator/SafetyMap.app","platformName":"iOS","deviceName":"iPhone7","newCommandTimeout":1200,"automationName":"XCUITest","device":"iphone","browserName":"LifeQA","sdkVersion":"10.2","CFBundleIdentifier":"com.life360.safetymap"}
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206 200 66 ms - 471 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5","4ccec28c-7c15-4242-9522-fbecfa4ae206"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/rect] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 554,\n    \"x\" : 112,\n    \"width\" : 151,\n    \"height\" : 50\n  },\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":112,"y":554}
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/location 200 110 ms - 89 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/size {}
[debug] [MJSONWP] Calling AppiumDriver.getSize() with args: ["0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5","4ccec28c-7c15-4242-9522-fbecfa4ae206"]
[debug] [XCUITest] Executing command 'getSize'
[debug] [JSONWP Proxy] Proxying [GET /element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/rect] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 554,\n    \"x\" : 112,\n    \"width\" : 151,\n    \"height\" : 50\n  },\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getSize() result: {"width":151,"height":50}
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/size 200 108 ms - 97 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/text {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/text] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/text] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Get Started\",\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101 with 4ccec28c-7c15-4242-9522-fbecfa4ae206
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/text 200 157 ms - 85 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/name {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/name] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/name] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeButton\",\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101 with 4ccec28c-7c15-4242-9522-fbecfa4ae206
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/name 200 109 ms - 95 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/enabled {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/enabled] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/enabled] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101 with 4ccec28c-7c15-4242-9522-fbecfa4ae206
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/enabled 200 109 ms - 76 
[HTTP] --> GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/selected {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/selected] to [GET http://localhost:8100/session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/selected] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\\/element\\/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5\\/selected -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\\/element\\/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5\\/selected\\\"\\n    );\\n}\",\n  \"sessionId\" : \"AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101\",\n  \"status\" : 1\n}"
[JSONWP Proxy] Replacing sessionId AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101 with 4ccec28c-7c15-4242-9522-fbecfa4ae206
[HTTP] <-- GET /wd/hub/session/4ccec28c-7c15-4242-9522-fbecfa4ae206/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/selected 200 4 ms - 383 
Found: 1 elements

---> Text: Get Started
---> TagName: XCUIElementTypeButton
---> Enabled: true
org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/selected -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/AF36CEB2-9E25-4C12-AFD6-C61BCEB4B101/element/0FFC8CF7-92BA-41A6-B1E8-4EED190E0EE5/selected"
    );
}
Command duration or timeout: 7 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Kranthis-MacBook-Pro.local', ip: '10.88.89.146', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/kranthi/Library/Developer/Xcode/DerivedData/SafetyMap-bepmknmoanbjekfkcdcesdxbonff/Build/Products/Debug-iphonesimulator/SafetyMap.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone7, platform=MAC, newCommandTimeout=1200, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=EE7A251E-1AEE-4BE1-AF41-77F616C00958}]
Session ID: 4ccec28c-7c15-4242-9522-fbecfa4ae206
java>

**Comment by dev-mobileboxlab** [comment]
Hi @KranthiReddyK,

Does this problem occur with all the elements?

**Comment by KranthiReddyK** [comment]
Good Question did not try with other elements. Will try and update
