### ISSUE TITLE
Windows path separators not acceptable while using appium.txt capabilities invokation

### ISSUE THREAD

**Issue by ehabibov** [mobileboxlab/appium-java-repl#6]
Trying to use `appium.txt` file to speed up process of launching REPL console but having obstacles that application URI component doesn't want to understand Windows path (because of backslashes) where located `appium.txt` with declared capabilities and as a result I'm getting error:
```java> android.start()
java.lang.UnsupportedOperationException: Can't convert 'file:${user.home}/appium.txt' to a valid URI
```

My current `${user.home}` system variable points to `C:\Users\Name.Surname\` and I even tried to update this system property during repl.jar launch with `-D` parameter in batch script but for some reason this does not work:
`%JAVA_HOME%\bin\java -Duser.home=C:/Users/Name.Surname/ -jar %PROJECT_DIR%\repl\appium-repl-0.1.0.jar`

I found an issue on https://github.com/lviggiano/owner/issues/123 where described the same behavior, so update, please, `org.aeonbits.owner` in your project dependencies to 1.0.9 version. I think it might help.

**Comment by dev-mobileboxlab** [comment]
Updated JavaRepl to [428](https://github.com/albertlatacz/java-repl/releases/tag/428)
